### ISSUE TITLE
Missing files after npm publish

### ISSUE THREAD

**Issue by egoist** [vue-land/create-vue-component#1]
Hmm it's weird that some files in `./template` are not published to npm:

https://cdn.jsdelivr.net/npm/cvc@1.0.2/template/

...compare with

https://github.com/vue-land/create-vue-component/tree/master/template

---

The package.json is correctly configured I think.

https://github.com/vue-land/create-vue-component/blob/f1b12fd20b4823d99985823f3d44033a7bd1c393/package.json#L13-L17

It didn't even work after I removed `files` key in `package.json`...

**Comment by egoist** [comment]
hmm it works after I rename `template/package.json` to `template/_package.json`

**Comment by egoist** [comment]
It's even weirder that it's fine to use `package.json` here https://github.com/egoist/template-nm/tree/master/template 😅

I don't know what I am doing now.

**Comment by gluons** [comment]
[yeoman/generator-webapp](https://github.com/yeoman/generator-webapp) do [the same thing as you](https://github.com/yeoman/generator-webapp/blob/d6127d122ba3d295175fb387e00895255a50464b/app/templates/_package.json) (It's currently in `master` while I'm writing this comment)

I don't know why 🤔

They start with [`_package.json`](https://github.com/yeoman/generator-webapp/blob/6dd842b6920096b6208c52e31e7805b9d5c53af2/app/templates/_package.json) in [the 2nd commit](https://github.com/yeoman/generator-webapp/tree/6dd842b6920096b6208c52e31e7805b9d5c53af2) in their repo.

**Comment by gluons** [comment]
Just copy your message to this issue for everyone who see this issue. 🙂 

> @egoist : "If `package.json` in sub directory is **valid json** it will be **applied** to that directory."
