### ISSUE TITLE
Npm publish

### ISSUE THREAD

**Issue by Remeic** [vue-land/create-vue-component#4]
Hi, maybe i made an error, but when i go to do `npm publish` i have this error
```
[19:02:18] error Could not resolve entry (./src/index.js)
undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-piuma@1.0.0 build: `bili`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-piuma@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

i have investigate a little, when i start project i rename index.js to index.vue for single file component, i think bili can't operate with vue extension so i add an entry on bili in package.json but i have an error on 

```
1 : <template>
2 :   <div>
3 :     <img :src="piumize">
```

**Comment by cristijora** [comment]
Hey @Remeic 
I think you could simply
```js
import MyComponent from './MyComponent.vue'

export default MyComponent
```
You need an entry js file so it can get transpiled into es5 or browser compatible code.
Besides that, the entry file could help you make your component to act as a plugin (if need that)
```js
const MyPlugin= {
  install (Vue) {
    // your plugin code here
  }
}
// Automatic installation if Vue has been added to the global scope.
if (typeof window !== 'undefined' && window.Vue) {
  window.Vue.use(MyPlugin)
}
export default MyPlugin
```

**Comment by Remeic** [comment]
Sorry for delay, university and work take me all time, thanks @cristijora  it works but seems i have some error with my single file component, like error 
`<img :src="piumize">`
unexpected token =
 or 
`<script>
export default {
  name: "vuepiuma",`
Adjacent JSX elements must be wrapped in an enclosing tag (6:0)

Here the project [vue-piuma
](https://github.com/lotrekagency/vue-piuma)

Can you link me a project or a resource so i can learn how i can made a good single file component?
Until now i follow the official documentation
Thanks in advance

**Comment by egoist** [comment]
Hmm you may be using an out-dated version of create-vue-component, the latest version added support for `.vue` component for publish. (https://github.com/vue-land/create-vue-component/commit/39e70b6e8c4665d360c24ea534007841332e5fac)

btw you should configure `bili` to bundle `src/index.vue` in this case:

![2017-11-28 11 35 01](https://user-images.githubusercontent.com/8784712/33301330-30bdfa06-d430-11e7-8911-4200171a7d89.png)
