### ISSUE TITLE
Use template html and external js?

### ISSUE THREAD

**Issue by mejobloggs** [vue-land/create-vue-component#6]
Hello,

I'm sorry to trouble you here. This isn't an issue with create-vue-component, I'm just a beginner looking for help using it.

How could I use this with normal Vue template html instead of the render(h) javascript?

How could I use an external js library (threejs) in my component without bundling it inside the component js?

Is there any way to add just a single thing to poi.config.js? By default there is no poi.config.js so I added one and now it won't run... I assume this is because I have now lost all the default settings because it sees an empty config file? I tried finding what the default settings should be so I could add to them, but I can't find anything.

Thanks for your time

**Comment by egoist** [comment]
> How could I use this with normal Vue template html instead of the render(h) javascript?

Do you mean single-file component? you can already use it.

> How could I use an external js library (threejs) in my component without bundling it inside the component js?

node modules are only bundled in `umd` format. if you want to exclude them: https://egoist.moe/bili/#/api?id=global

> By default there is no poi.config.js so I added one and now it won't run

it won't override the defaults if it's empty

**Comment by mejobloggs** [comment]
> Do you mean single-file component? you can already use it.

ah... do I just rename src/index.js to src/index.vue? I was trying to write single-file component code to index.js, but I was wrong to do that.

> node modules are only bundled in umd format. if you want to exclude them: https://egoist.moe/bili/#/api?id=global

Super cool 👍 

Thank you. Sorry I am slow to learn :)

**Comment by mejobloggs** [comment]
If I rename index.js to index.vue, 'yarn run example' works, but 'yarn run build' does not.

Error "No matched files to bundle"

**Comment by egoist** [comment]
yeah, since it uses `src/index.js` by default, check out https://egoist.moe/bili/#/api?id=input

**Comment by mejobloggs** [comment]
Thanks for your help
